version: "3.2"

services:
  cc:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1-internal
    ports:
      - target: 8090 # CCE
      - target: 8091 # CCE
      - target: 8092 # SPM      
    volumes: 
      - ./:/src 
    environment:
      - CC_PASSWORD
      - SAG_AQUARIUS=aquarius-dae.eur.ad.sag #added by ABG

  init:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1-internal
    environment: 
      - CC_ENV=cc
      - CC_SERVER=cc
      - CC_PASSWORD
      - SAG_AQUARIUS
    volumes: 
      - ./:/src 
      - ./clients/docker.properties:/root/.sag/cc.properties
    command: sagccant nodes -f /opt/softwareag/CommandCentral/init/build.xml
    depends_on: 
      - cc
      - dev1
      - dev2
      - devoracle
      - devtools

  dev1:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1.0.4-node
    ports: # export all known ports for easy testing, but dont statically bind them to allow CI
      - target: 8092 # SPM
      - target: 5555 # IS
    environment:
      - CC_AUTO_REGISTER=0

  dev2:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1.0.4-node
    ports: # export all known ports for easy testing, but dont statically bind them to allow CI
      - target: 8092 # SPM
      - target: 5555 # IS
    environment:
      - CC_AUTO_REGISTER=0

  devtools:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1.0.4-node
    ports: # export all known ports for easy testing, but dont statically bind them to allow CI
      - target: 8092 # SPM
    environment:
      - CC_AUTO_REGISTER=0

  devoracle:
    image: daerepository03.eur.ad.sag:4443/ccdevops/oracle:11.1
    ports: 
      - target: 1521
    environment: 
      - ORACLE_ALLOW_REMOTE=true

  test:
    image: daerepository03.eur.ad.sag:4443/ccdevops/commandcentral:10.1.0.4-client
    volumes: 
      - ./:/src 
      - .gradle/:/src/.gradle/       
      - ./clients/docker.properties:/root/.sag/cc.properties          
    environment: 
      - CC_SERVER=cc
      - CC_PASSWORD
      - CC_ENV=default
      - TEST_SUITE=**/AcceptanceTestSuite.class
      #- GRADLE_HOME=/src/.gradle
    command: 
      ./gradlew --no-daemon --refresh-dependencies up test -Denv=$CC_ENV -DtestSuite=$TEST_SUITE -Dcc=docker
